const toggle=document.querySelector('.nav-toggle');
const nav=document.querySelector('.site-nav');
if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});}

const sports=[
 ['kickboxing','any gym near you has a trial class. go once. give the bag your full attention for 20 minutes.'],['football','nearest turf, weekday night. someone’s always a player short. say yes.'],['tennis','a wall and one ball. hit against it for 20 minutes. no partner needed.'],['paddleboarding','rent one for an hour at any lake. balance, breathe, adjust. that is the whole experience.'],['deadlift','just the bar, no plates, learn the movement from one video. add weight next week, not today.'],['bhangra','search “basic bhangra steps”, living room, ten minutes. no one’s watching.'],['cycling','borrow or rent a bike. ride somewhere you’d normally drive.'],['basketball','any park hoop. shoot 50 free throws alone, count the makes, beat it next week.'],['running','20 minutes, slow enough to talk. you’re not training for anything. just go.'],['nunchucks','foam ones cost nothing online. backyard, slow figure-eights. attention before speed.'],['surfing','book a beginner lesson before you talk yourself out of it. standing up for 2 seconds counts.'],['calisthenics','a bar at the park. hang from it. try one pull-up. stay with it longer. that’s day one.'],['pool','any bar with a table. play a stranger. watch the angles. play again.'],['chess','a free app or a friend and a board. one game, no clock. notice the board, enjoy it.'],['ballroom','every city has a beginner social night. go alone, they pair you up. stay present with the rhythm.'],['quad biking','a rental near any hill town. alert for four minutes, then grinning.'],['pickleball','the easiest one to start. public court, borrowed paddle. track the ball, adjust, keep playing.'],['kayaking','rent one, one hour, calm water. it’s sitting down outdoors with a stick.'],['scuba','a discovery dive in a pool, no license needed. breathing underwater the first time rewires you.'],['paragliding','tandem flight. you run three steps and do nothing else. best money i’ve spent.'],['guitar','three chords, one song, friends building the groove together. the jam at the end of the reel is exactly that.']
];
const pick=document.querySelector('[data-pick]');
if(pick){let last=-1;pick.addEventListener('click',()=>{let i;do{i=Math.floor(Math.random()*sports.length)}while(i===last);last=i;document.querySelector('[data-play-start]').hidden=true;const result=document.querySelector('[data-play-result]');result.hidden=false;result.querySelector('[data-play-name]').textContent=sports[i][0];result.querySelector('[data-play-tip]').textContent=sports[i][1];});}
